default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 20

development:
  <<: *default
  username: postgres
  password: 1987simada
  host: localhost
  port: 5432
  database: reservation

test:
  <<: *default
  username: postgres
  password: 1987simada
  host: localhost
  port: 5432
  database: reservation_sandbox

production:
  <<: *default
  host: dpg-cjgol7j6fquc739gi0n0-a.singapore-postgres.render.com
  port: 10000
  database: reservation_0o4v
  username: reservation_0o4v_user
  password: DD7qik57EUbrqhdNINOsPhyiPUNKCQAA
  url: <%= ENV['postgres://reservation_0o4v_user:DD7qik57EUbrqhdNINOsPhyiPUNKCQAA@dpg-cjgol7j6fquc739gi0n0-a/reservation_0o4v'] %>

