default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 20
  username: postgres # PostgreSQLのユーザー名
  password: 1987simada # PostgreSQLのパスワード
  host: localhost
  port: 5432

development:
  <<: *default
  database: reservation # 作成したデータベース名

test:
  <<: *default
  database: reservation_sandbox

production:
  <<: *default
  database: reservation_production
